name: liboption-test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build liboption
      run: |
          meson build
          cd build
          ninja

  tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: |
          meson build
          cd build
          ninja test
